### ISSUE TITLE
Copyright Violation

### ISSUE THREAD

**Issue by Lilithbunny** [pbaykalov/hello-world#1]
Due to the recent updates of Pure, You have a repository that contains content that violates our copyright, please remove any repository that is related to Pure, failure to do so within 6-7 business days will result in the termination of said repository.

**Comment by pbaykalov** [comment]
> You have a repository that contains content that violates our copyright

![image](https://user-images.githubusercontent.com/54845956/188225000-05fd7cab-4103-4890-87d8-1233e90cee3f.png)


The MIT license which you granted to me by publishing your code can only be revoked if I violate the terms of it or if I fall under explicit condition for revocation of license. MIT license does not contain revocation clause and thus cannot be revoked as per USA law unless I violate it's terms.

**Comment by pbaykalov** [comment]
If you decide to move on with your intent as described your actions will constitute fraud.
